title: Tyler L. McIntosh
copyright: © Tyler L. McIntosh, 2024
description: Hi, I'm Tyler McIntosh! I'm currently a PhD student at CU Boulder co-advised by Dr. Jennifer Balch & Dr. Laura Dee. I am passionate about leveraging environmental data science to analyze coupled social-ecological systems and evaluate sustainable environmental solutions. Right now I work in wildfire systems.


lang: en

logo: /assets/images/tlm_headshot.jpg
accent_image: /assets/images/banner2.png
tagline: Scientist - Educator - Writer

remote_theme: hydecorp/hydejack@v9.1.6

menu:
  - title: About
    url: /about/
  - title: Research
    url: /research/
  - title: Publications
    url: /publications/
  - title: Teaching & Mentorship
    url: /teachingmentorship/
  - title: Creative work
    url: /creative/
  - title: CV
    url: /cv/

collections:
  pages:
    output: true
    permalink: /:path/

accent_color: rgb(79,177,186)

sass:
  sass_dir: _sass
  style: compressed

<!-- favicon: /assets/images/favicon.ico -->