
remote_theme: hydecorp/hydejack@v9.1.6

menu:
  - title: About
    url: /about/
  - title: Research
    url: /research/
  - title: Creative work
    url: /creative/
  - title: CV
    url: /cv/

collections:
  pages:
    output: true
    permalink: /:path/

accent_image: /assets/images/tlm_headshot.jpg
accent_color: rgb(79,177,186)