title: Tyler L. McIntosh
copyright: © Tyler L. McIntosh, 2024
description: Personal website of Tyler L. McIntosh

lang: en

logo: /assets/images/tlm_headshot.jpg
accent_image: /assets/images/banner2.png
tagline: Scientist - Creative

remote_theme: hydecorp/hydejack@v9.1.6

menu:
  - title: About
    url: /about/
  - title: Research
    url: /research/
  - title: Creative work
    url: /creative/
  - title: CV
    url: /cv/

collections:
  pages:
    output: true
    permalink: /:path/

accent_color: rgb(79,177,186)

sass:
  sass_dir: _sass
  style: compressed

<!-- favicon: /assets/images/favicon.ico -->