
remote_theme: hydecorp/hydejack@v9.1.6

menu:
  - title: About
    url:   /about/
  - title: Research
    url:   /research/
  - title: Creative work
    url:   /creative/
  - title: CV
    url:   /cv/

